export const portfolioConfig = {
  hero: {
    name: "Keshav",
    title: "A Software Engineer",
    subtitle: "I'm Keshav, a..",
    description:
      "Full-Stack Web Developer with a Passion for Building Scalable, AI/ML-Powered Solutions",
    image: "/profileImg2.jpg",
  },
  projects: [
    {
      id: "ClassMate",
      title: "ClassMate",
      description:
        "Built a full-stack campus management platform that streamlines student life with features like attendance tracking, internship aggregation, campus marketplace, ride-sharing, and secure role-based access—scalable, modular, and AI-ready.",
      image: "/ClassMate.png",
      demoUrl: "https://class-matefrontend.vercel.app/",
      githubUrl: "https://github.com/keshavagr273/ClassMate",
      docsUrl: "https://github.com/keshavagr273/ClassMate/blob/main/README.md",
      tags: ["React", "Node.js", "PostgreSQL", "JWT", "Tailwind CSS"],
    },
    {
      id: "Equity-Nest",
      title: "Equity Nest",
      description: "Equity Nest is a real-time stock trading platform built using Next.js, Express.js, and MongoDB. It offers live stock data, interactive TradingView charts, and portfolio management tools. The platform supports secure Google OAuth authentication and real-time updates via Socket.io. Designed for both desktop and mobile, it ensures a seamless trading experience.",
      image: "/equity.png",
      demoUrl: "https://equity-nest-mjil.vercel.app/",
      githubUrl: "https://github.com/keshavagr273/Equity-Nest.git",
      docsUrl: "https://github.com/keshavagr273/Equity-Nest/blob/main/README.md",
      tags: ["Next.js", "Express.js", "MongoDB", "Socket.io", "TradingView", "Google OAuth"],
    },
    {
      id: "Chat-App",
      title: "Real-Time Chat Application",
      description: "A modern full-stack chat platform built with React, Node.js, and MongoDB featuring real-time messaging via Socket.IO, video/voice calling with WebRTC, and JWT authentication. The app supports one-to-one and group chats with typing indicators, read receipts, emoji reactions, and message editing. Styled with Tailwind CSS and powered by Zustand for state management, it delivers a seamless and interactive communication experience.",
      image: "/chat.png",
      demoUrl: "https://chat-app-one-xi-68.vercel.app/",
      githubUrl: "https://github.com/keshavagr273/Chat-App",
      docsUrl: "https://github.com/keshavagr273/Chat-App/blob/main/README.md",
      tags: ["React", "Node.js", "MongoDB", "Socket.IO", "WebRTC", "JWT", "Tailwind CSS", "Zustand", "Vite"],
    },
    {
      id: "Minor-Project-Tracker",
      title: "Faculty Project Tracker",
      description: "A full-stack admin dashboard built with React, Node.js, and MongoDB for managing student project groups under faculty supervision. Features include real-time statistics, progress tracking with notes, alerts for inactive groups, advanced filtering and sorting, and CSV data export. Secured with JWT authentication and bcrypt, offering a modern responsive UI with smooth animations.",
      image: "/project.png",
      demoUrl: "https://minor-project-tracker.vercel.app/",
      githubUrl: "https://github.com/keshavagr273/MinorProject-Tracker",
      docsUrl: "https://github.com/keshavagr273/MinorProject-Tracker/blob/main/README.md",
      tags: ["React", "Node.js", "MongoDB", "JWT", "Vite", "Tailwind CSS", "Express"],
    },
    {
      id: "FreshFinds",
      title: "FreshFinds",
      description: "FreshFinds is a community-driven platform built with React, Node.js, and MongoDB that connects local vendors with nearby customers to resell unsold yet fresh food at discounted prices. It helps reduce food waste, support small businesses, and offers an easy, responsive interface for vendors to list items and customers to find affordable options.",
      image: "/FreshFinds.png",
      demoUrl: "https://fresh-finds-beige.vercel.app/",
      githubUrl: "https://github.com/keshavagr273/FreshFinds",
      docsUrl: "https://github.com/keshavagr273/FreshFinds/blob/main/README.md",
      tags: ["React", "Node.js", "MongoDB", "JavaScript", "CSS", "Food Redistribution"],
    },
    {
      id: "Heart-Disease-Predictor",
      title: "Heart Disease Predictor",
      description: "Built a web app to predict heart disease risk using user health data and a neural network model—featuring real-time results, a clean UI, and SMOTE-balanced training on BRFSS 2015 data.",
      image: "/heart1.png",
      demoUrl: "https://huggingface.co/spaces/keshav273/heart-pred-app",
      githubUrl: "https://github.com/keshavagr273/heart-disease-app",
      docsUrl: "https://github.com/keshavagr273/heart-disease-app/blob/master/README.md",
      tags: ["React", "Next.js", "Firebase", "NativeWind", "Zustand"],
    },
  ],
  skills: [
    // Tech skills
    { name: "Next.js", category: "tech" },
    { name: "React", category: "tech" },
    { name: "Node.js", category: "tech" },
    { name: "Express.js", category: "tech" },
    { name: "JavaScript", category: "tech" },
    { name: "TypeScript", category: "tech" },
    { name: "Java", category: "tech" },
    { name: "MongoDB", category: "tech" },
    { name: "PostgreSQL", category: "tech" },
    { name: "SQL", category: "tech" },
    { name: "Redis", category: "tech" },
    { name: "Redux", category: "tech" },
    { name: "API Development", category: "tech" },
    { name: "DBMS", category: "tech" },
    { name: "Computer Networking", category: "tech" },
    { name: "TensorFlow", category: "tech" },
    { name: "PyTorch", category: "tech" },
    { name: "scikit-learn", category: "tech" },
    { name: "Keras", category: "tech" },
    { name: "Computer Vision", category: "tech" },
    { name: "NLP", category: "tech" },
    { name: "Deep Learning", category: "tech" },
    { name: "Machine Learning", category: "tech" },
    // Tools skills
    { name: "Git/GitHub", category: "tools" },
    { name: "Docker", category: "tools" },
    { name: "Amazon Web Services", category: "tools" },
    { name: "Redis", category: "tools" },
    { name: "Supabase", category: "tools" },
  ],
  contact: {
    email: "keshavagrawal273@gmail.com",
    availability: "Available",
    responseTime: "Usually responds within 24 hours",
    socialLinks: [
      {
        name: "GitHub",
        url: "https://github.com/keshavagr273",
        icon: "github",
      },
      {
        name: "LinkedIn",
        url: "https://www.linkedin.com/in/keshav-agrawal-02b4861b0?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        icon: "linkedin",
      },
    ],
  },
  metadata: {
    title: "Keshav - Software Engineer",
    description:
      "Full-Stack Web Developer with a Passion for Building Scalable, AI/ML-Powered Solutions.",
    author: "Keshav",
    keywords: [
      "Full-Stack Web Developer",
      "AI",
      "ML",
      "Next.js",
      "React",
      "MongoDB",
      "Supabase",
      "Redux",
      "TensorFlow",
      "PyTorch",
      "Portfolio",
    ],
  },
};
